[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace=true
futures.workspace=true
tokio.workspace=true
tower.workspace=true
tracing.workspace=true
tracing-subscriber.workspace=true